type: object
additionalProperties: false
properties:
  redisUrl:
    $ref: '#/definitions/RedisUrl'
  postgresUrl:
    $ref: '#/definitions/PostgresUrl'
  botToken:
    $ref: '#/definitions/BotToken'
  useProxy:
    $ref: '#/definitions/UseProxy'
  proxyUrl:
    $ref: '#/definitions/ProxyUrl'
  groupChatId:
    $ref: '#/definitions/GroupChatId'
required:
  - redisUrl
  - postgresUrl
  - botToken
  - useProxy
  - proxyUrl
  - groupChatId
definitions:
  RedisUrl:
    type: string
    secret: true
  PostgresUrl:
    type: string
    secret: true
  BotToken:
    type: string
    secret: true
  UseProxy:
    type: boolean
  ProxyUrl:
    type: string
    secret: true
  GroupChatId:
    type: number

