type: object
additionalProperties: false
properties:
  redisUrl:
    type: string
    secret: true
  postgresUrl:
    type: string
    secret: true
  botToken:
    type: string
    secret: true
  useProxy:
    type: boolean
  proxyUrl:
    type: string
    secret: true
  groupChatId:
    type: number
  groupUrl:
    type: string
  channelChatId:
    type: number
  channelUrl:
    type: string
required:
  - redisUrl
  - postgresUrl
  - botToken
  - useProxy
  - proxyUrl
  - groupChatId
  - groupUrl
  - channelChatId
  - channelUrl

